using System.Globalization;
using OriginalCircuit.Altium.Diagnostics;
using OriginalCircuit.Altium.Models.Pcb;
using OriginalCircuit.Eda.Primitives;
using OriginalCircuit.Altium.Serialization.Binary;
using OriginalCircuit.Altium.Serialization.Compound;
using OriginalCircuit.Altium.Serialization.Writers;

namespace OriginalCircuit.Altium.Serialization.Readers;

/// <summary>
/// Reads PCB document (.PcbDoc) files.
/// PcbDoc files store primitives in separate storages by type
/// (e.g., [Arcs6], [Pads6], [Tracks6], etc.), each with Header and Data streams.
/// </summary>
public sealed class PcbDocReader
{
    private List<AltiumDiagnostic> _diagnostics = new();
    /// <summary>
    /// Reads a PcbDoc file from the specified path.
    /// </summary>
    /// <param name="path">Path to the .PcbDoc file.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The parsed PCB document.</returns>
    /// <exception cref="AltiumCorruptFileException">Thrown when the file cannot be parsed.</exception>
    /// <remarks>This method is not thread-safe. Create a new reader instance per thread.</remarks>
    public async ValueTask<PcbDocument> ReadAsync(string path, CancellationToken cancellationToken = default)
    {
        try
        {
            await using var accessor = await CompoundFileAccessor.OpenAsync(path, writable: false, cancellationToken).ConfigureAwait(false);
            return Read(accessor, cancellationToken);
        }
        catch (Exception ex) when (ex is not AltiumFileException and not OperationCanceledException
            and not OutOfMemoryException and not FileNotFoundException and not UnauthorizedAccessException
            and not DirectoryNotFoundException)
        {
            throw new AltiumCorruptFileException($"Failed to read PcbDoc file: {ex.Message}", filePath: path, innerException: ex);
        }
    }

    /// <summary>
    /// Reads a PcbDoc file from a stream.
    /// </summary>
    /// <param name="stream">A readable stream containing compound file data. The stream is not closed.</param>
    /// <returns>The parsed PCB document.</returns>
    /// <exception cref="AltiumCorruptFileException">Thrown when the stream cannot be parsed.</exception>
    /// <remarks>This method is not thread-safe. Create a new reader instance per thread.</remarks>
    public PcbDocument Read(Stream stream)
    {
        try
        {
            using var accessor = CompoundFileAccessor.Open(stream, leaveOpen: true);
            return Read(accessor);
        }
        catch (Exception ex) when (ex is not AltiumFileException and not OutOfMemoryException)
        {
            throw new AltiumCorruptFileException($"Failed to read PcbDoc file: {ex.Message}", innerException: ex);
        }
    }

    private static readonly HashSet<string> KnownStorageNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "FileHeader", "FileHeaderSix", "Board6", "Nets6", "Arcs6", "Pads6", "Vias6", "Tracks6",
        "Texts6", "Fills6", "Regions6", "ComponentBodies6", "Polygons6",
        "Components6", "WideStrings6", "EmbeddedBoards6",
        "Rules6", "Classes6", "DifferentialPairs6", "Rooms6", "SignalClasses",
        "SmartUnions", "UnionNames", "BoardRegions",
        "Dimensions6", "Coordinates6", "FromTos6", "Embeddeds6", "PrimitiveGuids",
        "UniqueIDPrimitiveInformation", "FileVersionInfo",
        "LayerKindMapping", "PadViaLibrary", "PadViaLibraryLinks", "Textures", "ModelsNoEmbed",
        "ShapeBasedRegions6", "ShapeBasedComponentBodies6", "PrimitiveParameters", "PadViaLibraryCache",
        "ExtendedPrimitiveInformation", "Models",
        "Design Rule Checker Options6", "Advanced Placer Options6", "Pin Swap Options6",
        "SimbeorCacheSection", "TMatchedNetLengthsViolation", "CustomShapes",
        "WaivedViolations", "PinPairsSection"
    };

    /// <summary>
    /// Editor/DRC parameter-block storages modeled as typed <see cref="PcbNamedParameterStorage"/> records
    /// (see that type). Each is read/written with its Header captured verbatim.
    /// </summary>
    private static readonly string[] NamedParameterStorageNames =
    {
        "Design Rule Checker Options6", "Advanced Placer Options6", "Pin Swap Options6",
        "SimbeorCacheSection", "TMatchedNetLengthsViolation", "CustomShapes",
        "WaivedViolations", "PinPairsSection"
    };

    private PcbDocument Read(CompoundFileAccessor accessor, CancellationToken cancellationToken = default)
    {
        _diagnostics = new List<AltiumDiagnostic>();
        var document = new PcbDocument();

        // The legacy FileHeader stream is a fixed 24-byte constant stamp (no per-document data); it is
        // fully modeled and regenerated by PcbDocWriter, so nothing needs to be captured here.
        ReadFileHeaderSix(accessor, document);

        // Read wide strings (used by text primitives)
        var wideStrings = ReadWideStrings(accessor);

        // Read board-level parameters
        ReadBoard(accessor, document);
        ReadNets(accessor, document);

        cancellationToken.ThrowIfCancellationRequested();

        // Read each primitive type from its dedicated storage
        ReadArcs(accessor, document, cancellationToken);
        ReadPads(accessor, document, cancellationToken);
        ReadVias(accessor, document, cancellationToken);
        ReadTracks(accessor, document, cancellationToken);
        ReadTexts(accessor, document, wideStrings, cancellationToken);
        ReadFills(accessor, document, cancellationToken);
        ReadRegions(accessor, document, cancellationToken);
        ReadBoardRegions(accessor, document, cancellationToken);
        ReadShapeBased(accessor, "ShapeBasedRegions6", 0x0B, document.ShapeBasedRegions);
        ReadShapeBased(accessor, "ShapeBasedComponentBodies6", 0x0C, document.ShapeBasedComponentBodies);
        ReadPrimitiveParameters(accessor, document);
        ReadExtendedPrimitiveInformation(accessor, document);
        ReadNamedParameterStorages(accessor, document);
        ReadEmbeddedModels(accessor, document);
        ReadDocumentPrimitiveGuids(accessor, document);
        ReadDocumentPrimitiveUniqueIds(accessor, document);
        var fviStorage = accessor.TryGetStorage("FileVersionInfo");
        if (fviStorage != null && fviStorage.TryGetStream("Data", out var fviData))
            document.FileVersionInfo = PcbLibReader.ParseFileVersionInfo(fviData.GetData());
        var lkmStorage = accessor.TryGetStorage("LayerKindMapping");
        if (lkmStorage != null && lkmStorage.TryGetStream("Data", out var lkmData))
            document.LayerKindMapping = PcbLibReader.ParseLayerKindMapping(lkmData.GetData());
        document.PadViaLibrary = PcbLibReader.ParsePadViaLibrary(accessor.RootStorage, "PadViaLibrary");
        document.PadViaLibraryCache = PcbLibReader.ParsePadViaLibrary(accessor.RootStorage, "PadViaLibraryCache");
        ReadComponentBodies(accessor, document, cancellationToken);
        ReadPolygons(accessor, document, cancellationToken);
        ReadComponents(accessor, document, cancellationToken);
        ReadEmbeddedBoards(accessor, document, cancellationToken);

        // Assign document-level pads to their parent components using the binary component index
        AssignPadsToComponents(document);

        // Read parameter-block storages
        ReadRules(accessor, document);
        ReadClasses(accessor, document);
        ReadSignalClasses(accessor, document);
        ReadSmartUnions(accessor, document);
        ReadUnionNames(accessor, document);
        ReadDifferentialPairs(accessor, document);
        ReadRooms(accessor, document);

        // Capture unknown storages for round-trip fidelity
        ReadAdditionalStreams(accessor, document);

        document.Diagnostics = _diagnostics;
        return document;
    }

    private static void ReadFileHeaderSix(CompoundFileAccessor accessor, PcbDocument document)
    {
        // FileHeaderSix carries the modern version stamp + per-document GUID (fileheaders.md §4).
        // Model the GUID; everything else is a Reserved constant. Null when the stream is absent so
        // the writer reproduces "no FileHeaderSix" exactly (round-trip) while a from-scratch document
        // keeps its default fresh GUID.
        var stream = accessor.TryGetStream("FileHeaderSix");
        if (stream == null)
        {
            document.FileGuid = null;
            return;
        }

        var data = stream.GetData();
        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        var versionBlockLen = reader.ReadInt32();           // [u32 len][b len][version text] — Reserved
        if (versionBlockLen <= 0) { document.FileGuid = null; return; }
        reader.Skip(reader.ReadByte());
        if (!reader.HasMore) { document.FileGuid = null; return; }
        reader.Skip(8);                                     // 5.01 double — Reserved

        if (!reader.HasMore) { document.FileGuid = null; return; }
        var guidBlockLen = reader.ReadInt32();              // [u32 len][b len][{GUID}] — Identity
        if (guidBlockLen <= 0) { document.FileGuid = null; return; }
        var guidLen = reader.ReadByte();
        var guidBytes = new byte[guidLen];
        reader.ReadExact(guidBytes);
        var guidText = AltiumEncoding.Windows1252.GetString(guidBytes);
        document.FileGuid = Guid.TryParse(guidText, out var g) ? g : null;
    }

    private void ReadAdditionalStreams(CompoundFileAccessor accessor, PcbDocument document)
    {
        var additional = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);

        foreach (var item in accessor.EnumerateChildren(accessor.RootStorage))
        {
            // Record every root entry so the writer can reproduce known storages that were
            // present but empty (e.g. DifferentialPairs6) instead of omitting them.
            if (item.IsStorage)
                document.PresentStorages.Add(item.Name);

            if (KnownStorageNames.Contains(item.Name))
                continue;

            if (item.IsStorage)
            {
                var childStorage = item.AsStorage();
                foreach (var stream in accessor.EnumerateStreams(childStorage))
                {
                    try
                    {
                        additional[$"{item.Name}/{stream.Name}"] = stream.GetData();
                    }
                    catch (Exception ex) when (ex is EndOfStreamException or InvalidDataException or IOException)
                    {
                        _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning, $"Failed to read stream '{item.Name}/{stream.Name}': {ex.Message}"));
                    }
                }
            }
            else
            {
                var rootStream = item.AsStream();
                try
                {
                    additional[item.Name] = rootStream.GetData();
                }
                catch (Exception ex) when (ex is EndOfStreamException or InvalidDataException or IOException)
                {
                    _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning, $"Failed to read stream '{item.Name}': {ex.Message}"));
                }
            }
        }

        if (additional.Count > 0)
            document.AdditionalStreams = additional;
    }

    private static List<string> ReadWideStrings(CompoundFileAccessor accessor)
    {
        var result = new List<string>();
        var storage = accessor.TryGetStorage("WideStrings6");
        if (storage == null)
            return result;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return result;

        var data = dataStream.GetData();

        // WideStrings6 is a sequence of [u32 text_index][u32 byte_len][UTF-16LE string incl. null].
        var pos = 0;
        while (pos + 8 <= data.Length)
        {
            var index = BitConverter.ToInt32(data, pos);
            var byteLen = BitConverter.ToInt32(data, pos + 4);
            pos += 8;
            if (byteLen < 0 || pos + byteLen > data.Length)
                break;
            var s = System.Text.Encoding.Unicode.GetString(data, pos, byteLen);
            pos += byteLen;
            var nul = s.IndexOf('\0');
            if (nul >= 0)
                s = s.Substring(0, nul);
            if (index < 0)
                continue;
            while (result.Count <= index)
                result.Add(string.Empty);
            result[index] = s;
        }

        return result;
    }

    private static void ReadBoard(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("Board6");
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        var parameters = PcbLibReader.ReadParameterBlock(reader, out var rawBoard);
        if (parameters.Count > 0)
        {
            document.BoardParameters = parameters;
            document.BoardParametersOrdered = PcbLibReader.ParseParametersOrdered(rawBoard);
        }
    }

    private static void ReadNets(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("Nets6");
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        while (reader.HasMore)
        {
            var parameters = PcbLibReader.ReadParameterBlock(reader, out var rawNet);
            if (parameters.Count == 0)
                continue;

            document.AddNet(ParseNet(PcbLibReader.ParseParametersOrdered(rawNet)));
        }
    }

    // Parses a Nets6 record from its ordered parameter list into a fully typed PcbNet, so the writer
    // can regenerate the exact bytes without replaying the captured parameter block.
    private static PcbNet ParseNet(List<KeyValuePair<string, string>> ordered)
    {
        var net = new PcbNet();
        foreach (var (key, value) in ordered)
        {
            switch (key.ToUpperInvariant())
            {
                case "SELECTION": net.Selection = ParamBool(value); break;
                case "LAYER": net.Layer = value; break;
                case "LOCKED": net.Locked = ParamBool(value); break;
                case "POLYGONOUTLINE": net.PolygonOutline = ParamBool(value); break;
                case "USERROUTED": net.UserRouted = ParamBool(value); break;
                case "KEEPOUT": net.Keepout = ParamBool(value); break;
                case "UNIONINDEX": net.UnionIndex = ParamInt(value); break;
                case "PRIMITIVELOCK": net.PrimitiveLock = ParamBool(value); break;
                case "NAME": net.Name = value; break;
                case "VISIBLE": net.Visible = ParamBool(value); break;
                case "COLOR": net.Color = ParamInt(value); break;
                case "LOOPREMOVAL": net.LoopRemoval = ParamBool(value); break;
                case "OVERRIDECOLORFORDRAW": net.OverrideColorForDraw = ParamBool(value); break;
                case "UNIQUEID": net.UniqueId = value; break;
                case "JUMPERSVISIBLE": net.JumpersVisible = ParamBool(value); break;
                case "ROUTEDLENGTH": net.RoutedLength = ParamInt(value); break;
                case "MANHATTANLENGTH": net.ManhattanLength = ParamInt(value); break;
                case "TARGETLENGTH": net.TargetLengthUnits = ParamMilUnits(value); break;
                case "MRVIASIZE": net.MinRoutedViaSizeUnits = ParamMilUnits(value); break;
                case "MRVIAHOLE": net.MinRoutedViaHoleUnits = ParamMilUnits(value); break;
                case "SIGNALLENGTH": net.SignalLength = ParamInt(value); break;
                case "SIGNALDELAY": net.SignalDelay = ParamDouble(value); break;
                case "DELAYTOTAL": net.DelayTotal = ParamDouble(value); break;
                case "CURRENTTOTAL": net.CurrentTotal = ParamDouble(value); break;
                case "RESISTANCETOTAL": net.ResistanceTotal = ParamDouble(value); break;
                default:
                    if (key.EndsWith("_MRWIDTH", StringComparison.OrdinalIgnoreCase))
                    {
                        net.LayerMinRoutedWidths ??= new List<PcbNetLayerWidth>();
                        net.LayerMinRoutedWidths.Add(new PcbNetLayerWidth
                        {
                            LayerKey = key[..^"_MRWIDTH".Length],
                            WidthUnits = ParamMilUnits(value),
                        });
                    }
                    break;
            }
        }
        return net;
    }

    private static bool ParamBool(string value) => value.Equals("TRUE", StringComparison.OrdinalIgnoreCase);

    private static int ParamInt(string value) =>
        int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v) ? v : 0;

    private static double ParamDouble(string value) =>
        double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : 0;

    // Parses a width token like "11.811mil" into internal coordinate units (1 mil = 10000), rounding
    // to the nearest unit (Coord.FromMils truncates, which would lose the last unit on round-trip).
    private static int ParamMilUnits(string value)
    {
        var s = value.EndsWith("mil", StringComparison.OrdinalIgnoreCase) ? value[..^3] : value;
        return double.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out var mils)
            ? (int)Math.Round(mils * 10000.0)
            : 0;
    }

    // Parses a mil token (e.g. "1338.5827mil") into a Coord via rounded raw units.
    private static Coord ParamMilCoord(string value) => Coord.FromRaw(ParamMilUnits(value));

    // Decodes the UNICODE=EXISTS wrapping: a param block with non-Latin-1 text carries the full
    // value as a UNICODE__<KEY>=<comma-decimal UTF-16 code units> companion (the inline value has the
    // >255 codepoints stripped). Replace each base key with its true decoded value and drop the
    // UNICODE markers, so downstream typed parsing sees the real strings.
    internal static void DecodeUnicodeParameters(Dictionary<string, string> p)
    {
        if (!p.TryGetValue("UNICODE", out var flag) || !flag.Equals("EXISTS", StringComparison.OrdinalIgnoreCase))
            return;
        var remove = new List<string> { "UNICODE" };
        foreach (var kvp in p)
        {
            if (!kvp.Key.StartsWith("UNICODE__", StringComparison.OrdinalIgnoreCase))
                continue;
            remove.Add(kvp.Key);
            var baseKey = kvp.Key.Substring("UNICODE__".Length);
            var sb = new System.Text.StringBuilder();
            foreach (var code in kvp.Value.Split(','))
                if (int.TryParse(code, NumberStyles.Integer, CultureInfo.InvariantCulture, out var cu))
                    sb.Append((char)cu);
            p[baseKey] = sb.ToString();
        }
        foreach (var k in remove)
            p.Remove(k);
    }

    private void ReadParameterBlockStorage(CompoundFileAccessor accessor, string storageName,
        Action<Dictionary<string, string>, List<KeyValuePair<string, string>>> addItem)
    {
        var storage = accessor.TryGetStorage(storageName);
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        try
        {
            using var ms = new MemoryStream(data);
            using var reader = new BinaryFormatReader(ms, leaveOpen: true);

            while (reader.HasMore)
            {
                var parameters = PcbLibReader.ReadParameterBlock(reader, out var raw);
                if (parameters.Count == 0)
                    continue;

                addItem(parameters, PcbLibReader.ParseParametersOrdered(raw));
            }
        }
        catch (Exception ex) when (ex is EndOfStreamException or InvalidDataException or FormatException or OverflowException)
        {
            _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning,
                $"Failed to fully parse {storageName}: {ex.Message}", storageName));
        }
    }

    private void ReadRules(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("Rules6");
        if (storage == null)
            return;
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;
        var data = dataStream.GetData();

        // Rules6 records use a 2-byte leader + 4-byte length + null-terminated text layout,
        // unlike Nets6/Classes6 which omit the leader. The leader varies per record and must
        // be preserved for round-trip.
        var pos = 0;
        while (pos + 6 <= data.Length)
        {
            var leader = (ushort)(data[pos] | (data[pos + 1] << 8));
            var length = BitConverter.ToInt32(data, pos + 2);
            pos += 6;
            if (length <= 0 || pos + length > data.Length)
                break;

            var nul = Array.IndexOf(data, (byte)0, pos, length);
            var textLen = nul >= 0 ? nul - pos : length;
            var text = AltiumEncoding.Windows1252.GetString(data, pos, textLen);
            pos += length;

            var parameters = PcbLibReader.ParseParameters(text);
            DecodeUnicodeParameters(parameters);
            var ruleKind = parameters.TryGetValue("RULEKIND", out var rk) ? rk : string.Empty;
            var rule = CreateRuleForKind(ruleKind);
            rule.RawLeader = leader;
            rule.Parameters = parameters;
            rule.ReadCommonHeader(parameters);
            if (rule.IsModeled)
            {
                rule.ReadBody(parameters);
                rule.ReadOrdered(PcbLibReader.ParseParametersOrdered(text));
            }
            else
                rule.RawParametersOrdered = PcbLibReader.ParseParametersOrdered(text); // kind not yet typed
            document.AddRule(rule);
        }
    }

    // Maps a RULEKIND to its typed rule class. Kinds with dynamic per-layer key blocks (Width,
    // DiffPairsRouting, RoutingLayers) and any unknown kind fall back to the base PcbRule (replay).
    private static PcbRule CreateRuleForKind(string kind) => kind switch
    {
        "Clearance" or "BoardOutlineClearance" => new PcbClearanceRule(),
        "ComponentClearance" => new PcbComponentClearanceRule(),
        "Width" => new PcbWidthRule(),
        "DiffPairsRouting" => new PcbDiffPairsRoutingRule(),
        "AssemblyTestpoint" => new PcbAssemblyTestpointRule(),
        "FabricationTestpoint" => new PcbFabricationTestpointRule(),
        "AssemblyTestPointUsage" or "SilkToBoardRegionClearance" or "UnpouredPolygon" or "UnRoutedNet" => new PcbHeaderOnlyRule(),
        "FabricationTestPointUsage" => new PcbFabricationTestPointUsageRule(),
        "FanoutControl" => new PcbFanoutControlRule(),
        "Height" => new PcbHeightRule(),
        "HoleSize" => new PcbHoleSizeRule(),
        "HoleToHoleClearance" => new PcbHoleToHoleClearanceRule(),
        "LayerPairs" => new PcbLayerPairsRule(),
        "Length" => new PcbLengthRule(),
        "MatchedLengths" => new PcbMatchedLengthsRule(),
        "MinimumSolderMaskSliver" => new PcbMinimumSolderMaskSliverRule(),
        "NetAntennae" => new PcbNetAntennaeRule(),
        "PasteMaskExpansion" => new PcbPasteMaskExpansionRule(),
        "PlaneClearance" => new PcbPlaneClearanceRule(),
        "PlaneConnect" => new PcbPlaneConnectRule(),
        "PolygonConnect" => new PcbPolygonConnectRule(),
        "RoutingCorners" => new PcbRoutingCornersRule(),
        "RoutingLayers" => new PcbRoutingLayersRule(),
        "RoutingPriority" => new PcbRoutingPriorityRule(),
        "RoutingTopology" => new PcbRoutingTopologyRule(),
        "RoutingVias" => new PcbRoutingViasRule(),
        "ShortCircuit" => new PcbShortCircuitRule(),
        "SignalStimulus" => new PcbSignalStimulusRule(),
        "SilkToSilkClearance" => new PcbSilkToSilkClearanceRule(),
        "SilkToSolderMaskClearance" => new PcbSilkToSolderMaskClearanceRule(),
        "SolderMaskExpansion" => new PcbSolderMaskExpansionRule(),
        "SupplyNets" => new PcbSupplyNetsRule(),
        _ => new PcbRule(),
    };

    private void ReadClasses(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "Classes6", (_, ordered) => document.AddClass(ParseObjectClass(ordered)));
    }

    // Parses a Classes6 record from its ordered parameter list into a fully typed PcbObjectClass.
    private static PcbObjectClass ParseObjectClass(List<KeyValuePair<string, string>> ordered)
    {
        var oc = new PcbObjectClass();
        foreach (var (key, value) in ordered)
        {
            switch (key.ToUpperInvariant())
            {
                case "SELECTION": oc.Selection = ParamBool(value); break;
                case "LAYER": oc.Layer = value; break;
                case "LOCKED": oc.Locked = ParamBool(value); break;
                case "POLYGONOUTLINE": oc.PolygonOutline = ParamBool(value); break;
                case "USERROUTED": oc.UserRouted = ParamBool(value); break;
                case "KEEPOUT": oc.Keepout = ParamBool(value); break;
                case "UNIONINDEX": oc.UnionIndex = ParamInt(value); break;
                case "NAME": oc.Name = value; break;
                case "KIND": oc.Kind = value; break;
                case "SUPERCLASS": oc.SuperClass = ParamBool(value); break;
                case "AUTOGENERATEDCLASS": oc.AutoGeneratedClass = ParamBool(value); break;
                case "SELECTED": oc.Selected = ParamBool(value); break;
                case "SCHAUTOGENERATEDCLUSTER": oc.SchAutoGeneratedCluster = ParamBool(value); break;
                case "UNIQUEID": oc.UniqueId = value; break;
                case "AUTOGENERATEDCLASSKIND": oc.AutoGeneratedClassKind = ParamInt(value); break;
                default:
                    if (key.Length > 1 && (key[0] == 'M' || key[0] == 'm') && char.IsDigit(key[1]))
                        oc.Members.Add(value);
                    break;
            }
        }
        return oc;
    }

    private void ReadSignalClasses(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "SignalClasses", (_, ordered) =>
        {
            var sc = new PcbSignalClass();
            foreach (var (key, value) in ordered)
            {
                switch (key.ToUpperInvariant())
                {
                    case "SELECTION": sc.Selection = ParamBool(value); break;
                    case "LAYER": sc.Layer = value; break;
                    case "LOCKED": sc.Locked = ParamBool(value); break;
                    case "POLYGONOUTLINE": sc.PolygonOutline = ParamBool(value); break;
                    case "USERROUTED": sc.UserRouted = ParamBool(value); break;
                    case "KEEPOUT": sc.Keepout = ParamBool(value); break;
                    case "UNIONINDEX": sc.UnionIndex = ParamInt(value); break;
                    case "NAME": sc.Name = value; break;
                    case "KIND": sc.Kind = ParamInt(value); break;
                    case "SUPERCLASS": sc.SuperClass = ParamBool(value); break;
                    case "SELECTED": sc.Selected = ParamBool(value); break;
                    case "SCHAUTOGENERATEDCLUSTER": sc.SchAutoGeneratedCluster = ParamBool(value); break;
                    case "UNIQUEID": sc.UniqueId = value; break;
                }
            }
            document.AddSignalClass(sc);
        });
    }

    // The common-primitive prefix that begins every SmartUnions member sub-block, in order.
    private static readonly string[] UnionPrefixKeys =
        { "SELECTION", "LAYER", "LOCKED", "POLYGONOUTLINE", "USERROUTED", "KEEPOUT", "UNIONINDEX" };

    private void ReadSmartUnions(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "SmartUnions", (_, ordered) =>
            document.AddSmartUnion(ParseSmartUnion(ordered)));
    }

    // Splits a SmartUnions record's ordered key list into its member sub-blocks. Each member begins
    // at a SELECTION key (the start of the common-primitive prefix); the seven prefix keys are typed,
    // the remainder kept as an ordered member-specific list (preserving duplicates / indexed arrays).
    private static PcbSmartUnion ParseSmartUnion(List<KeyValuePair<string, string>> ordered)
    {
        var union = new PcbSmartUnion();
        PcbUnionMember? cur = null;
        var prefixPos = 0;
        foreach (var kv in ordered)
        {
            if (kv.Key.Equals("SELECTION", StringComparison.OrdinalIgnoreCase))
            {
                cur = new PcbUnionMember();
                union.Members.Add(cur);
                prefixPos = 0;
            }
            if (cur == null)
            {
                // Defensive: content before the first SELECTION (not seen in the corpus) — keep it
                // in a leading member so nothing is lost.
                cur = new PcbUnionMember();
                union.Members.Add(cur);
                prefixPos = UnionPrefixKeys.Length;
            }
            if (prefixPos < UnionPrefixKeys.Length
                && kv.Key.Equals(UnionPrefixKeys[prefixPos], StringComparison.OrdinalIgnoreCase))
            {
                AssignUnionPrefix(cur, prefixPos, kv.Value);
                prefixPos++;
            }
            else
            {
                cur.Parameters.Add(kv);
            }
        }
        return union;
    }

    private static void AssignUnionPrefix(PcbUnionMember m, int pos, string value)
    {
        switch (pos)
        {
            case 0: m.Selection = value.Equals("TRUE", StringComparison.OrdinalIgnoreCase); break;
            case 1: m.Layer = value; break;
            case 2: m.Locked = value.Equals("TRUE", StringComparison.OrdinalIgnoreCase); break;
            case 3: m.PolygonOutline = value.Equals("TRUE", StringComparison.OrdinalIgnoreCase); break;
            case 4: m.UserRouted = value.Equals("TRUE", StringComparison.OrdinalIgnoreCase); break;
            case 5: m.Keepout = value.Equals("TRUE", StringComparison.OrdinalIgnoreCase); break;
            case 6:
                if (int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var ui))
                    m.UnionIndex = ui;
                break;
        }
    }

    private void ReadUnionNames(CompoundFileAccessor accessor, PcbDocument document)
    {
        // UnionNames/Data = [u32 count][per record: u32 union_index][u32 byte_count][UTF-16LE name + 00 00].
        var storage = accessor.TryGetStorage("UnionNames");
        if (storage == null) return;
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null) return;
        var data = dataStream.GetData();
        if (data.Length < 4) return;
        var pos = 0;
        var count = BitConverter.ToUInt32(data, pos); pos += 4;
        for (var r = 0; r < count && pos + 8 <= data.Length; r++)
        {
            var unionIndex = BitConverter.ToInt32(data, pos); pos += 4;
            var byteCount = (int)BitConverter.ToUInt32(data, pos); pos += 4;
            if (pos + byteCount > data.Length) break;
            var name = System.Text.Encoding.Unicode.GetString(data, pos, byteCount).TrimEnd('\0');
            pos += byteCount;
            document.AddUnionName(new PcbUnionName { UnionIndex = unionIndex, Name = name });
        }
    }

    private void ReadDifferentialPairs(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "DifferentialPairs6", (_, ordered) =>
        {
            var pair = new PcbDifferentialPair();
            foreach (var (key, value) in ordered)
            {
                switch (key.ToUpperInvariant())
                {
                    case "SELECTION": pair.Selection = ParamBool(value); break;
                    case "LAYER": pair.Layer = value; break;
                    case "LOCKED": pair.Locked = ParamBool(value); break;
                    case "POLYGONOUTLINE": pair.PolygonOutline = ParamBool(value); break;
                    case "USERROUTED": pair.UserRouted = ParamBool(value); break;
                    case "KEEPOUT": pair.Keepout = ParamBool(value); break;
                    case "UNIONINDEX": pair.UnionIndex = ParamInt(value); break;
                    case "POSITIVENETNAME": pair.PositiveNetName = value; break;
                    case "NEGATIVENETNAME": pair.NegativeNetName = value; break;
                    case "NAME": pair.Name = value; break;
                    case "GATHERCONTROL": pair.GatherControl = ParamBool(value); break;
                    case "UNIQUEID": pair.UniqueId = value; break;
                }
            }
            document.AddDifferentialPair(pair);
        });
    }

    private void ReadRooms(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "Rooms6", (parameters, _) =>
        {
            var room = new PcbRoom();
            if (parameters.TryGetValue("NAME", out var name))
                room.Name = name;
            if (parameters.TryGetValue("UNIQUEID", out var uniqueId))
                room.UniqueId = uniqueId;

            document.AddRoom(room);
        });
    }

    private void ReadArcs(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Arcs6", reader =>
        {
            var arc = PcbLibReader.ReadArc(reader);
            if (arc != null)
                document.AddArc(arc);
        }, cancellationToken);
    }

    private void ReadPads(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Pads6", reader =>
        {
            var pad = PcbLibReader.ReadPad(reader);
            if (pad != null)
                document.AddPad(pad);
        }, cancellationToken);
    }

    /// <summary>
    /// Assigns document-level pads to their parent component using the component index
    /// stored in the binary pad record. This populates each component's Pads collection
    /// so consumers can access pads through the component rather than searching by proximity.
    /// </summary>
    private static void AssignPadsToComponents(PcbDocument document)
    {
        var components = document.Components.OfType<PcbComponent>().ToList();
        if (components.Count == 0)
            return;

        foreach (var pad in document.Pads.OfType<PcbPad>())
        {
            var idx = pad.ComponentIndex;
            if (idx >= 0 && idx < components.Count)
            {
                components[idx].AddPad(pad);
            }
        }
    }

    private void ReadVias(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Vias6", reader =>
        {
            var via = PcbLibReader.ReadVia(reader);
            if (via != null)
                document.AddVia(via);
        }, cancellationToken);
    }

    private void ReadTracks(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Tracks6", reader =>
        {
            var track = PcbLibReader.ReadTrack(reader);
            if (track != null)
                document.AddTrack(track);
        }, cancellationToken);
    }

    private void ReadTexts(CompoundFileAccessor accessor, PcbDocument document, List<string> wideStrings, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Texts6", reader =>
        {
            var text = PcbLibReader.ReadText(reader, wideStrings);
            if (text != null)
                document.AddText(text);
        }, cancellationToken);
    }

    private void ReadFills(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Fills6", reader =>
        {
            var fill = PcbLibReader.ReadFill(reader);
            if (fill != null)
                document.AddFill(fill);
        }, cancellationToken);
    }

    private void ReadRegions(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "Regions6", reader =>
        {
            var region = PcbLibReader.ReadRegion(reader);
            if (region != null)
                document.AddRegion(region);
        }, cancellationToken);
    }

    private static void ReadDocumentPrimitiveGuids(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("PrimitiveGuids");
        if (storage == null) return;
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null) return;
        var data = dataStream.GetData();
        for (var pos = 0; pos + 24 <= data.Length; pos += 24)
        {
            document.PrimitiveGuids.Add(new PcbPrimitiveGuid
            {
                TypeId = BitConverter.ToUInt32(data, pos),
                Index = BitConverter.ToUInt32(data, pos + 4),
                Guid = new Guid(data.AsSpan(pos + 8, 16)),
            });
        }
    }

    private static void ReadDocumentPrimitiveUniqueIds(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("UniqueIDPrimitiveInformation");
        if (storage == null) return;
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null) return;
        document.PrimitiveUniqueIds.AddRange(PcbLibReader.ParsePrimitiveUniqueIdRecords(dataStream.GetData()));
    }

    private void ReadBoardRegions(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        // BoardRegions records use the same [u8 0x0B][region body] framing as Regions6.
        ReadPrimitiveStorage(accessor, "BoardRegions", reader =>
        {
            var region = PcbLibReader.ReadRegion(reader);
            if (region != null)
                document.AddBoardRegion(region);
        }, cancellationToken);
    }

    private void ReadPrimitiveParameters(CompoundFileAccessor accessor, PcbDocument document)
    {
        var storage = accessor.TryGetStorage("PrimitiveParameters");
        if (storage == null) return;
        if (PcbLibReader.GetChildStream(storage, "Header") is { } hdr)
        {
            var hb = hdr.GetData();
            if (hb.Length >= 4) document.PrimitiveParametersHeader = BitConverter.ToInt32(hb, 0);
        }
        ReadParameterBlockStorage(accessor, "PrimitiveParameters", (parameters, ordered) =>
            document.PrimitiveParameters.Add(new PcbParameterRecord { Parameters = parameters, OrderedParameters = ordered }));
    }

    private void ReadExtendedPrimitiveInformation(CompoundFileAccessor accessor, PcbDocument document)
    {
        ReadParameterBlockStorage(accessor, "ExtendedPrimitiveInformation", (parameters, ordered) =>
        {
            var info = new PcbExtendedPrimitiveInfo { Parameters = parameters, OrderedParameters = ordered };
            if (parameters.TryGetValue("PRIMITIVEINDEX", out var idx) &&
                int.TryParse(idx, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i))
                info.PrimitiveIndex = i;
            if (parameters.TryGetValue("PRIMITIVEOBJECTID", out var oid)) info.PrimitiveObjectId = oid;
            if (parameters.TryGetValue("TYPE", out var type)) info.Type = type;
            if (parameters.TryGetValue("SOLDERMASKEXPANSIONMODE", out var sme)) info.SolderMaskExpansionMode = sme;
            if (parameters.TryGetValue("SOLDERMASKEXPANSION_MANUAL", out var smm)) info.SolderMaskExpansionManual = smm;
            if (parameters.TryGetValue("PASTEMASKEXPANSIONMODE", out var pme)) info.PasteMaskExpansionMode = pme;
            if (parameters.TryGetValue("PASTEMASKEXPANSION_MANUAL", out var pmm)) info.PasteMaskExpansionManual = pmm;
            document.ExtendedPrimitiveInfo.Add(info);
        });
    }

    private static void ReadEmbeddedModels(CompoundFileAccessor accessor, PcbDocument document)
    {
        // Root Models storage: Data = per-model metadata (length-prefixed |KEY=VALUE| blocks),
        // numbered Models/<n> streams = zlib STEP payloads. Shared parse with the PcbLib Library/Models.
        var storage = accessor.TryGetStorage("Models");
        if (storage == null) return;
        document.ModelsStoragePresent = true;

        var dataBytes = PcbLibReader.GetChildStream(storage, "Data")?.GetData();
        var models = PcbModel.ParseModels(dataBytes,
            i => PcbLibReader.GetChildStream(storage, i.ToString(CultureInfo.InvariantCulture))?.GetData());
        document.Models.AddRange(models);
    }

    private void ReadNamedParameterStorages(CompoundFileAccessor accessor, PcbDocument document)
    {
        foreach (var name in NamedParameterStorageNames)
        {
            var storage = accessor.TryGetStorage(name);
            if (storage == null) continue;

            var entry = new PcbNamedParameterStorage { Name = name };
            if (PcbLibReader.GetChildStream(storage, "Header") is { } hdr)
            {
                var hb = hdr.GetData();
                if (hb.Length >= 4) entry.Header = BitConverter.ToInt32(hb, 0);
            }

            var dataStream = PcbLibReader.GetChildStream(storage, "Data");
            var data = dataStream?.GetData() ?? Array.Empty<byte>();
            if (data.Length > 0)
            {
                try
                {
                    using var ms = new MemoryStream(data);
                    using var reader = new BinaryFormatReader(ms, leaveOpen: true);
                    while (reader.HasMore)
                    {
                        var parameters = PcbLibReader.ReadParameterBlock(reader, out var raw);
                        if (parameters.Count == 0) continue;
                        entry.Records.Add(new PcbParameterRecord
                        {
                            Parameters = parameters,
                            OrderedParameters = PcbLibReader.ParseParametersOrdered(raw),
                        });
                    }
                }
                catch (Exception ex) when (ex is EndOfStreamException or InvalidDataException or FormatException or OverflowException)
                {
                    _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning,
                        $"Failed to fully parse {name}: {ex.Message}", name));
                }
            }

            document.NamedParameterStorages.Add(entry);
        }
    }

    private void ReadShapeBased(CompoundFileAccessor accessor, string storageName, byte typeByte, List<PcbShapeBasedRegion> target)
    {
        // ShapeBasedRegions6 (0x0B) / ShapeBasedComponentBodies6 (0x0C) records are
        // [u8 type][u32 sr1_len][header][props][outline of extended 37-byte vertices][holes]. The
        // standard region reader can't parse the extended vertices, so we parse the Data buffer directly.
        var storage = accessor.TryGetStorage(storageName);
        if (storage == null) return;
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null) return;
        var data = dataStream.GetData();
        var pos = 0;
        try
        {
            while (pos < data.Length && data[pos] == typeByte)
                target.Add(ParseShapeBasedRegion(data, ref pos));
        }
        catch (Exception ex) when (ex is IndexOutOfRangeException or ArgumentOutOfRangeException)
        {
            _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning,
                $"Failed to fully parse {storageName}: {ex.Message}", storageName));
        }
    }

    private static PcbShapeBasedRegion ParseShapeBasedRegion(byte[] data, ref int pos)
    {
        var r = new PcbShapeBasedRegion { TypeByte = data[pos] };
        pos += 1;                                                       // type byte (0x0B / 0x0C)
        pos += 4;                                                       // SubRecord-1 length (derived on write = body length)
        r.Layer = data[pos]; pos += 1;
        r.Flags1 = data[pos]; pos += 1;
        r.Flags2 = data[pos]; pos += 1;
        r.NetIndex = BitConverter.ToUInt16(data, pos); pos += 2;
        r.PolygonIndex = BitConverter.ToUInt16(data, pos); pos += 2;
        r.ComponentIndex = BitConverter.ToUInt16(data, pos); pos += 2;
        pos += 5;                                                       // constant: union-index-none FF FF FF FF + reserved 00
        var holeCount = BitConverter.ToUInt16(data, pos); pos += 2;
        pos += 2;                                                       // constant: reserved 00 00
        var propsLen = BitConverter.ToInt32(data, pos); pos += 4;
        var fullText = System.Text.Encoding.UTF8.GetString(data, pos, propsLen); pos += propsLen;
        var trimmed = fullText.TrimEnd('\0');
        r.PropsInnerNulls = fullText.Length - trimmed.Length;
        if (trimmed.Length > 0)
            foreach (var seg in trimmed.Split('|'))
            {
                var eq = seg.IndexOf('=');
                r.Properties.Add(eq < 0
                    ? new KeyValuePair<string, string?>(seg, null)
                    : new KeyValuePair<string, string?>(seg[..eq], seg[(eq + 1)..]));
            }
        if (pos < data.Length && data[pos] == 0) { r.PropsHasTrailingNull = true; pos += 1; }
        var outlineCount = BitConverter.ToUInt32(data, pos); pos += 4;
        for (var i = 0; i <= outlineCount; i++)   // disk count is N, but N+1 vertices are stored
        {
            var v = new PcbExtendedVertex
            {
                IsRoundRaw = data[pos], X = BitConverter.ToInt32(data, pos + 1), Y = BitConverter.ToInt32(data, pos + 5),
                CenterX = BitConverter.ToInt32(data, pos + 9), CenterY = BitConverter.ToInt32(data, pos + 13),
                Radius = BitConverter.ToInt32(data, pos + 17), StartAngle = BitConverter.ToDouble(data, pos + 21),
                EndAngle = BitConverter.ToDouble(data, pos + 29),
            };
            pos += 37;
            r.Outline.Add(v);
        }
        for (var h = 0; h < holeCount; h++)
        {
            var hv = BitConverter.ToUInt32(data, pos); pos += 4;
            var hole = new List<(double, double)>((int)hv);
            for (var i = 0; i < hv; i++) { hole.Add((BitConverter.ToDouble(data, pos), BitConverter.ToDouble(data, pos + 8))); pos += 16; }
            r.Holes.Add(hole);
        }
        return r;
    }

    private void ReadComponentBodies(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        ReadPrimitiveStorage(accessor, "ComponentBodies6", reader =>
        {
            var body = PcbLibReader.ReadComponentBody(reader);
            if (body != null)
                document.AddComponentBody(body);
        }, cancellationToken);
    }

    private static void ReadPolygons(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        var storage = accessor.TryGetStorage("Polygons6");
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        while (reader.HasMore)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var parameters = PcbLibReader.ReadParameterBlock(reader, out var rawPolygon);
            if (parameters.Count == 0)
                continue;

            DecodeUnicodeParameters(parameters);
            document.AddPolygon(ParsePolygon(parameters));
        }
    }

    /// <summary>
    /// Parses a layer value that can be either a numeric ID (e.g. "1") or a name (e.g. "TOP").
    /// </summary>
    private static int ParseLayerValue(string layerStr)
    {
        if (int.TryParse(layerStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var numeric))
            return numeric;

        // Fall back to layer name lookup
        return PcbLibWriter.LayerNameToByte(layerStr);
    }

    private static bool TryGetBool(Dictionary<string, string> parameters, string key, out bool value)
    {
        value = false;
        if (!parameters.TryGetValue(key, out var str))
            return false;
        value = string.Equals(str, "TRUE", StringComparison.OrdinalIgnoreCase);
        return true;
    }

    private static bool TryGetBoolAny(Dictionary<string, string> parameters, out bool value, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (TryGetBool(parameters, key, out value))
                return true;
        }
        value = false;
        return false;
    }

    private static bool TryGetIntAny(Dictionary<string, string> parameters, out int value, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (parameters.TryGetValue(key, out var str) && int.TryParse(str, NumberStyles.Integer, CultureInfo.InvariantCulture, out value))
                return true;
        }
        value = 0;
        return false;
    }

    private static bool TryGetCoordAny(Dictionary<string, string> parameters, out Coord value, params string[] keys)
    {
        if (TryGetIntAny(parameters, out var raw, keys))
        {
            value = Coord.FromRaw(raw);
            return true;
        }
        value = default;
        return false;
    }

    private static readonly HashSet<string> PolygonKnownKeys = new(StringComparer.OrdinalIgnoreCase)
    {
        "SELECTION", "LAYER", "LOCKED", "POLYGONOUTLINE", "USERROUTED", "KEEPOUT", "UNIONINDEX",
        "PRIMITIVELOCK", "POLYGONTYPE", "POUROVER", "REMOVEDEAD", "GRIDSIZE", "TRACKWIDTH", "HATCHSTYLE",
        "USEOCTAGONS", "MINPRIMLENGTH", "SHELVED", "RESTORELAYER", "RESTORENET", "REMOVEISLANDSBYAREA",
        "REMOVENECKS", "AREATHRESHOLD", "ARCRESOLUTION", "NECKWIDTHTHRESHOLD", "NECKWIDTHFROMRULE",
        "POUROVERSTYLE", "NAME", "POURINDEX", "IGNOREVIOLATIONS", "COPPERINVALIDATE", "AUTONAME",
        "OPTIMALVOIDROTATION", "OBEYPOLYGONCUTOUT", "NET",
    };

    // Parses a Polygons6 record into a fully typed PcbPolygon (no ordered-param replay). The per-vertex
    // KIND/VX/VY/CX/CY/SA/EA/R keys are index-contiguous (0..N); NAME is a comma-separated ASCII-code list.
    private static PcbPolygon ParsePolygon(Dictionary<string, string> p)
    {
        bool B(string k) => p.TryGetValue(k, out var v) && v.Equals("TRUE", StringComparison.OrdinalIgnoreCase);
        int I(string k) => p.TryGetValue(k, out var v) && int.TryParse(v, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) ? n : 0;

        var poly = new PcbPolygon
        {
            Selection = B("SELECTION"),
            Layer = ParseLayerValue(p.GetValueOrDefault("LAYER", "0")),
            Locked = B("LOCKED"),
            PolygonOutline = B("POLYGONOUTLINE"),
            UserRouted = B("USERROUTED"),
            IsKeepout = B("KEEPOUT"),
            UnionIndex = I("UNIONINDEX"),
            PrimitiveLock = B("PRIMITIVELOCK"),
            PolygonType = p.TryGetValue("POLYGONTYPE", out var pty) ? pty : "Polygon",
            PourOver = B("POUROVER"),
            RemoveDead = B("REMOVEDEAD"),
            Grid = ParamMilCoord(p.GetValueOrDefault("GRIDSIZE", "0")),
            TrackSize = ParamMilCoord(p.GetValueOrDefault("TRACKWIDTH", "0")),
            HatchStyle = p.TryGetValue("HATCHSTYLE", out var hs) ? hs : "Solid",
            UseOctagons = B("USEOCTAGONS"),
            MinTrack = ParamMilCoord(p.GetValueOrDefault("MINPRIMLENGTH", "0")),
            IsHidden = B("SHELVED"),
            RestoreLayer = p.TryGetValue("RESTORELAYER", out var rl) ? rl : "UNKNOWN",
            RestoreNet = p.TryGetValue("RESTORENET", out var rn) ? rn : string.Empty,
            RemoveIslandsByArea = B("REMOVEISLANDSBYAREA"),
            RemoveNarrowNecks = B("REMOVENECKS"),
            ArcApproximation = ParamMilCoord(p.GetValueOrDefault("ARCRESOLUTION", "0")),
            NeckWidthThreshold = ParamMilCoord(p.GetValueOrDefault("NECKWIDTHTHRESHOLD", "0")),
            PourOverStyle = I("POUROVERSTYLE"),
            PourIndex = I("POURINDEX"),
            IgnoreViolations = B("IGNOREVIOLATIONS"),
            Net = p.GetValueOrDefault("NET", string.Empty),
            UniqueId = p.GetValueOrDefault("UNIQUEID"),
        };
        if (p.TryGetValue("AREATHRESHOLD", out var at) && decimal.TryParse(at, NumberStyles.Float, CultureInfo.InvariantCulture, out var area))
            poly.AreaThreshold = area;
        if (p.ContainsKey("OPTIMALVOIDROTATION"))
            poly.OptimalVoidRotation = B("OPTIMALVOIDROTATION");
        if (p.ContainsKey("OBEYPOLYGONCUTOUT"))
            poly.ObeyPolygonCutout = B("OBEYPOLYGONCUTOUT");
        if (p.ContainsKey("NECKWIDTHFROMRULE"))
            poly.NeckWidthFromRule = B("NECKWIDTHFROMRULE");
        if (p.ContainsKey("COPPERINVALIDATE"))
            poly.CopperInvalidate = B("COPPERINVALIDATE");
        if (p.ContainsKey("AUTONAME"))
            poly.AutoGenerateName = B("AUTONAME");
        if (p.TryGetValue("NAME", out var nm))
            poly.Name = DecodeAsciiCodes(nm);

        for (var i = 0; p.ContainsKey($"VX{i}"); i++)
        {
            var v = new PcbPolygonVertex
            {
                Kind = I($"KIND{i}"),
                X = ParamMilCoord(p.GetValueOrDefault($"VX{i}", "0")),
                Y = ParamMilCoord(p.GetValueOrDefault($"VY{i}", "0")),
                CenterX = ParamMilCoord(p.GetValueOrDefault($"CX{i}", "0")),
                CenterY = ParamMilCoord(p.GetValueOrDefault($"CY{i}", "0")),
                StartAngle = ParamDouble(p.GetValueOrDefault($"SA{i}", "0")),
                EndAngle = ParamDouble(p.GetValueOrDefault($"EA{i}", "0")),
                Radius = ParamMilCoord(p.GetValueOrDefault($"R{i}", "0")),
            };
            poly.OutlineVertices.Add(v);
            poly.AddVertex(new CoordPoint(v.X, v.Y));
        }

        foreach (var kvp in p)
        {
            if (PolygonKnownKeys.Contains(kvp.Key) || IsPolygonVertexKey(kvp.Key))
                continue;
            (poly.AdditionalParameters ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase))[kvp.Key] = kvp.Value;
        }
        return poly;
    }

    private static bool IsPolygonVertexKey(string key)
    {
        // KIND{n}/VX{n}/VY{n}/CX{n}/CY{n}/SA{n}/EA{n}/R{n}
        int i = 0;
        foreach (var pfx in new[] { "KIND", "VX", "VY", "CX", "CY", "SA", "EA", "R" })
            if (key.StartsWith(pfx, StringComparison.OrdinalIgnoreCase) && key.Length > pfx.Length && char.IsDigit(key[pfx.Length])) { i = 1; break; }
        return i == 1;
    }

    private static string DecodeAsciiCodes(string s)
    {
        if (string.IsNullOrEmpty(s)) return string.Empty;
        var sb = new System.Text.StringBuilder();
        foreach (var part in s.Split(','))
            if (int.TryParse(part, NumberStyles.Integer, CultureInfo.InvariantCulture, out var code)) sb.Append((char)code);
        return sb.ToString();
    }

    private static void ReadEmbeddedBoards(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        var storage = accessor.TryGetStorage("EmbeddedBoards6");
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        while (reader.HasMore)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var parameters = PcbLibReader.ReadParameterBlock(reader, out var rawBoard);
            if (parameters.Count == 0)
                continue;

            document.AddEmbeddedBoard(ParseEmbeddedBoard(PcbLibReader.ParseParametersOrdered(rawBoard)));
        }
    }

    // Parses an EmbeddedBoards6 record from its ordered parameter list into a fully typed model.
    private static PcbEmbeddedBoard ParseEmbeddedBoard(List<KeyValuePair<string, string>> ordered)
    {
        var b = new PcbEmbeddedBoard();
        foreach (var (key, value) in ordered)
        {
            switch (key.ToUpperInvariant())
            {
                case "SELECTION": b.Selection = ParamBool(value); break;
                case "LAYER": b.Layer = value; break;
                case "LOCKED": b.Locked = ParamBool(value); break;
                case "POLYGONOUTLINE": b.PolygonOutline = ParamBool(value); break;
                case "USERROUTED": b.UserRouted = ParamBool(value); break;
                case "KEEPOUT": b.IsKeepout = ParamBool(value); break;
                case "UNIONINDEX": b.UnionIndex = ParamInt(value); break;
                case "X1": b.X1Location = ParamMilCoord(value); break;
                case "Y1": b.Y1Location = ParamMilCoord(value); break;
                case "X2": b.X2Location = ParamMilCoord(value); break;
                case "Y2": b.Y2Location = ParamMilCoord(value); break;
                case "ROTATION": b.Rotation = ParamDouble(value); break;
                case "ISVIEWPORT": b.IsViewport = ParamBool(value); break;
                case "VIEWPORTX1": b.ViewportX1 = ParamMilCoord(value); break;
                case "VIEWPORTY1": b.ViewportY1 = ParamMilCoord(value); break;
                case "VIEWPORTX2": b.ViewportX2 = ParamMilCoord(value); break;
                case "VIEWPORTY2": b.ViewportY2 = ParamMilCoord(value); break;
                case "VIEWPORTSCALE": b.ViewportScale = ParamDouble(value); break;
                case "VIEWPORTVISIBLE": b.ViewportVisible = ParamBool(value); break;
                case "VIEWPORTTITLE": b.ViewportTitle = value; break;
                case "FONTNAME": b.TitleFontName = value; break;
                case "FONTSIZE": b.TitleFontSize = ParamInt(value); break;
                case "FONTCOLOR": b.TitleFontColor = ParamInt(value); break;
                case "VISIBLELAYERS": b.VisibleLayers = value; break;
                case "DOCUMENTPATH": b.DocumentPath = value; break;
                case "X": b.X = ParamMilCoord(value); break;
                case "Y": b.Y = ParamMilCoord(value); break;
                case "ROWSPACING": b.RowSpacing = ParamMilCoord(value); break;
                case "COLSPACING": b.ColSpacing = ParamMilCoord(value); break;
                case "ROWCOUNT": b.RowCount = ParamInt(value); break;
                case "COLCOUNT": b.ColCount = ParamInt(value); break;
                case "MIRROR": b.MirrorFlag = ParamBool(value); break;
                case "ORIGINMODE": b.OriginMode = ParamInt(value); break;
            }
        }
        return b;
    }

    /// <summary>
    /// Parses a coordinate value in "NNNNmil" format (e.g., "1338.5827mil") to a Coord.
    /// Also handles raw integer values for compatibility with programmatically saved files.
    /// </summary>
    private static bool TryParseMilCoord(Dictionary<string, string> parameters, string key, out Coord value)
    {
        value = default;
        if (!parameters.TryGetValue(key, out var str))
            return false;

        var trimmed = str.AsSpan().Trim();

        // If the string has a "mil" suffix, parse as mils
        if (trimmed.EndsWith("mil", StringComparison.OrdinalIgnoreCase))
        {
            var numPart = trimmed[..^3];
            if (double.TryParse(numPart, System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var mils))
            {
                value = Coord.FromMils(mils);
                return true;
            }
            return false;
        }

        // No "mil" suffix — treat as raw integer (internal coordinate units)
        if (int.TryParse(trimmed, NumberStyles.Integer, CultureInfo.InvariantCulture, out var raw))
        {
            value = Coord.FromRaw(raw);
            return true;
        }

        return false;
    }

    private static void ReadComponents(CompoundFileAccessor accessor, PcbDocument document, CancellationToken cancellationToken)
    {
        var storage = accessor.TryGetStorage("Components6");
        if (storage == null)
            return;

        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        // Components are stored as parameter blocks (not binary primitives)
        while (reader.HasMore)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var parameters = PcbLibReader.ReadParameterBlock(reader, out var rawComp);
            if (parameters.Count == 0)
                continue;

            DecodeUnicodeParameters(parameters);
            var component = new PcbComponent();
            ApplyComponentParameters(component, parameters);
            document.AddComponent(component);
        }
    }

    // Parses a Components6 record's parameters into a fully typed PcbComponent. Optional keys whose
    // presence is not inferable from the value are modeled as nullable fields (null => omit on write).
    private static void ApplyComponentParameters(PcbComponent c, Dictionary<string, string> p)
    {
        string? S(string k) => p.TryGetValue(k, out var v) ? v : null;
        bool Bv(string k) => p.TryGetValue(k, out var v) && v.Equals("TRUE", StringComparison.OrdinalIgnoreCase);
        int? NI(string k) => p.TryGetValue(k, out var v) && int.TryParse(v, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) ? n : null;

        c.Selection = Bv("SELECTION");
        if (S("LAYER") is { } layer) c.Layer = ParseLayerValue(layer);
        c.Locked = Bv("LOCKED");
        c.PolygonOutline = Bv("POLYGONOUTLINE");
        c.UserRouted = Bv("USERROUTED");
        c.IsKeepout = Bv("KEEPOUT");
        c.PrimitiveLock = Bv("PRIMITIVELOCK");
        if (S("X") is { } xs) c.X = ParamMilCoord(xs);
        if (S("Y") is { } ys) c.Y = ParamMilCoord(ys);
        if (S("PATTERN") is { } pat) c.Name = pat;
        c.Description = S("DESCRIPTION");
        c.NameOn = Bv("NAMEON");
        c.CommentOn = Bv("COMMENTON");
        c.Comment = S("COMMENT");
        c.LockStrings = Bv("LOCKSTRINGS");
        if (NI("GROUPNUM") is { } gn) c.GroupNum = gn;
        if (NI("COUNT") is { } cnt) c.Count = cnt;
        if (S("ROTATION") is { } rot && double.TryParse(rot.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var rotation))
            c.Rotation = rotation;
        if (S("HEIGHT") is { } h) c.Height = ParamMilCoord(h);
        c.NameAutoPosition = NI("NAMEAUTOPOSITION");
        c.CommentAutoPosition = NI("COMMENTAUTOPOSITION");
        if (NI("UNIONINDEX") is { } ui) c.UnionIndex = ui;
        if (p.ContainsKey("ENABLEPINSWAPPING")) c.EnablePinSwapping = Bv("ENABLEPINSWAPPING");
        if (p.ContainsKey("ENABLEPARTSWAPPING")) c.EnablePartSwapping = Bv("ENABLEPARTSWAPPING");
        if (p.ContainsKey("ENABLED")) c.Enabled = Bv("ENABLED");
        c.FlippedOnLayer = Bv("FLIPPEDONLAYER");
        c.IsBGA = Bv("ISBGA");
        c.ComponentKind = NI("COMPONENTKIND");
        c.ComponentKindVersion2 = NI("COMPONENTKINDVERSION2");
        c.ChannelOffset = NI("CHANNELOFFSET");
        c.SourceDesignator = S("SOURCEDESIGNATOR");
        c.SourceUniqueId = S("SOURCEUNIQUEID");
        c.SourceHierarchicalPath = S("SOURCEHIERARCHICALPATH");
        c.SourceFootprintLibrary = S("SOURCEFOOTPRINTLIBRARY");
        c.SourceComponentLibrary = S("SOURCECOMPONENTLIBRARY");
        c.SourceLibReference = S("SOURCELIBREFERENCE");
        c.SourceDescription = S("SOURCEDESCRIPTION");
        c.FootprintDescription = S("FOOTPRINTDESCRIPTION");
        c.SourceCompDesignItemID = S("SOURCECOMPDESIGNITEMID");
        c.SourceCompLibIdentifierKind = NI("SOURCECOMPLIBIDENTIFIERKIND");
        c.SourceCompLibraryIdentifier = S("SOURCECOMPLIBRARYIDENTIFIER");
        c.VaultGUID = S("VAULTGUID");
        c.ItemGUID = S("ITEMGUID");
        c.ItemRevisionGUID = S("ITEMREVISIONGUID");
        c.ModelHash = S("MODELHASH");
        c.PackageSpecificHash = S("PACKAGESPECIFICHASH");
        c.DefaultPCB3DModel = S("DEFAULTPCB3DMODEL");
        if (S("UNIQUEID") is { } uid) c.UniqueId = uid;
        if (p.ContainsKey("JUMPERSVISIBLE")) c.JumpersVisible = Bv("JUMPERSVISIBLE");
        if (S("AREA") is { } ar && decimal.TryParse(ar, NumberStyles.Float, CultureInfo.InvariantCulture, out var area))
            c.Area = area;

        // Preserve any keys the typed model doesn't cover (forward-compat; empty for the corpus).
        foreach (var kvp in p)
        {
            if (!ComponentKnownKeys.Contains(kvp.Key))
                (c.AdditionalParameters ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase))[kvp.Key] = kvp.Value;
        }
    }

    private static readonly HashSet<string> ComponentKnownKeys = new(StringComparer.OrdinalIgnoreCase)
    {
        "SELECTION", "LAYER", "LOCKED", "POLYGONOUTLINE", "USERROUTED", "KEEPOUT", "PRIMITIVELOCK",
        "X", "Y", "PATTERN", "DESCRIPTION", "NAMEON", "COMMENTON", "COMMENT", "LOCKSTRINGS",
        "GROUPNUM", "COUNT", "ROTATION", "HEIGHT", "NAMEAUTOPOSITION", "COMMENTAUTOPOSITION",
        "UNIONINDEX", "ENABLEPINSWAPPING", "ENABLEPARTSWAPPING", "ENABLED", "FLIPPEDONLAYER", "ISBGA", "COMPONENTKIND", "COMPONENTKINDVERSION2",
        "CHANNELOFFSET", "SOURCEDESIGNATOR", "SOURCEUNIQUEID", "SOURCEHIERARCHICALPATH",
        "SOURCEFOOTPRINTLIBRARY", "SOURCECOMPONENTLIBRARY", "SOURCELIBREFERENCE", "SOURCEDESCRIPTION",
        "FOOTPRINTDESCRIPTION", "SOURCECOMPDESIGNITEMID", "SOURCECOMPLIBIDENTIFIERKIND",
        "SOURCECOMPLIBRARYIDENTIFIER", "VAULTGUID", "ITEMGUID", "ITEMREVISIONGUID", "MODELHASH",
        "PACKAGESPECIFICHASH", "DEFAULTPCB3DMODEL", "UNIQUEID", "JUMPERSVISIBLE", "AREA",
    };

    /// <summary>
    /// Reads a primitive storage section. Each storage has a Header stream (record count)
    /// and a Data stream. Each record is prefixed with an object ID byte (same as PcbLib),
    /// followed by the type-specific binary data.
    /// </summary>
    private void ReadPrimitiveStorage(
        CompoundFileAccessor accessor,
        string storageName,
        Action<BinaryFormatReader> readPrimitive,
        CancellationToken cancellationToken = default)
    {
        var storage = accessor.TryGetStorage(storageName);
        if (storage == null)
            return;

        // Read primitives from Data stream
        var dataStream = PcbLibReader.GetChildStream(storage, "Data");
        if (dataStream == null)
            return;

        var data = dataStream.GetData();
        if (data.Length == 0)
            return;

        using var ms = new MemoryStream(data);
        using var reader = new BinaryFormatReader(ms, leaveOpen: true);

        var recordIndex = 0;
        while (reader.HasMore)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                // Each record is prefixed with an object ID byte
                reader.ReadByte();
                readPrimitive(reader);
                recordIndex++;
            }
            catch (EndOfStreamException)
            {
                // A truncated/corrupt record aborts this storage; surface it instead of silently
                // dropping every remaining primitive (which would make a partial parse look complete).
                _diagnostics.Add(new AltiumDiagnostic(DiagnosticSeverity.Warning,
                    $"Truncated or corrupt record at index {recordIndex} in '{storageName}'; remaining primitives in this storage were skipped.",
                    storageName, recordIndex));
                break;
            }
        }
    }
}
